### ISSUE TITLE
Error: Cannot find module 'eslint-config-xo'

### ISSUE THREAD

**Issue by RootMale** [google/eslint-config-google#10]
/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:398
throw e;
^

Error: Cannot find module 'eslint-config-xo'
Referenced from: google
Referenced from: /home/shav/IdeaProjects/ds-orders-web/.eslintrc.js
at Object.ModuleResolver.resolve (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/util/module-resolver.js:74:19)
at resolve (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:475:33)
at load (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:492:24)
at /home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:388:36
at Array.reduceRight (native)
at applyExtends (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:365:28)
at load (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:527:22)
at /home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:388:36
at Array.reduceRight (native)
at applyExtends (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:365:28)
at Object.load (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:527:22)
at loadConfig (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:67:33)
at getLocalConfig (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:129:23)
at Config.getConfig (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:230:22)
at processText (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:149:27)
at CLIEngine.executeOnText (/home/shav/IdeaProjects/ds-orders-web/node_modules/ds-web-gulp/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:666:26)

Process finished with exit code 1

shav@shav-OptiPlex-3020:~/IdeaProjects/ds-orders-web$ node -v
v4.4.1
shav@shav-OptiPlex-3020:~/IdeaProjects/ds-orders-web$ npm -v
2.14.20

**Comment by sindresorhus** [comment]
Ensure you're using the latest version of ESLint.

**Comment by reywright** [comment]
Also: make sure you're not running eslint on node_modules folders.
